import { describe, expect, it, mock } from "bun:test";
import type { SubtitleTrack } from "../src/subtitles.ts";
import { MWEB_USER_AGENT } from "../src/youtube-mweb-config.ts";

const VISITOR_DATA = "visitor-data-test-123";
const INTEGRITY_TOKEN = "integrity-token-test-xyz";
const PO_TOKEN = `pot-${VISITOR_DATA}`;
const mockYoutubeFetch = mock(
	async (_input: RequestInfo | URL): Promise<Response> =>
		new Response("WEBVTT\n\n00:00.000 --> 00:01.000\nHello", {
			status: 200,
			headers: { "content-type": "text/vtt" },
		}),
);

mock.module("../src/botguard-page.ts", () => ({
	executeBotGuard: mock(async (): Promise<string> => "botguard-response-test"),
	mintPoToken: mock(async (_token: string, id: string): Promise<string> => `pot-${id}`),
	resetBotGuardPage: mock(async (): Promise<void> => undefined),
}));

mock.module("../src/token-service.ts", () => ({
	getOrRefreshSession: mock(async () => ({
		visitorData: VISITOR_DATA,
		visitorBoundPoToken: PO_TOKEN,
		integrityToken: INTEGRITY_TOKEN,
		expiresAt: Date.now() + 3600_000,
	})),
	fetchPoToken: mock(async (videoId: string) => ({
		visitorData: VISITOR_DATA,
		visitorBoundPoToken: PO_TOKEN,
		videoBoundPoToken: `pot-${videoId}`,
		poToken: PO_TOKEN,
		streamingPot: `pot-${videoId}`,
	})),
}));

const frTrack = {
	baseUrl: "https://www.youtube.com/api/timedtext?lang=fr",
	name: { simpleText: "French" },
	languageCode: "fr",
};

const asrTrack = {
	baseUrl: "https://www.youtube.com/api/timedtext?v=video&lang=en&kind=asr&expire=999",
	name: { simpleText: "English (auto-generated)" },
	languageCode: "en",
	kind: "asr",
	vssId: "a.en",
};

const mockFetchCaptionTracks = mock(
	async (_videoId: string, _visitorData: string, _poToken: string) => [frTrack, asrTrack],
);

mock.module("../src/youtube-caption-tracks.ts", () => ({
	fetchCaptionTracks: mockFetchCaptionTracks,
}));

mock.module("../src/innertube.ts", () => ({
	fetchVisitorData: mock(async (): Promise<string> => VISITOR_DATA),
	fetchChallenge: mock(async () => ({})),
	fetchIntegrityToken: mock(async () => ({ integrityToken: INTEGRITY_TOKEN })),
}));

describe("fetchSubtitles", () => {
	it("maps caption tracks to SubtitleTrack shape", async () => {
		const { fetchSubtitles } = await import("../src/subtitles.ts");
		const result: SubtitleTrack[] = await fetchSubtitles("dQw4w9WgXcQ");

		expect(result).toHaveLength(2);

		expect(result[0]).toEqual({
			url: "https://www.youtube.com/api/timedtext?lang=fr",
			mimeType: "application/ttml+xml",
			languageTag: "fr",
			displayLanguageName: "French",
			isAutoGenerated: false,
		});

		expect(result[1]).toEqual({
			url: "https://www.youtube.com/api/timedtext?v=video&lang=en&kind=asr&expire=999",
			mimeType: "application/ttml+xml",
			languageTag: "en",
			displayLanguageName: "English (auto-generated)",
			isAutoGenerated: true,
		});
		expect(mockFetchCaptionTracks).toHaveBeenLastCalledWith("dQw4w9WgXcQ", VISITOR_DATA, PO_TOKEN);
	});

	it("returns empty array when no caption tracks", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => []);
		const { fetchSubtitles } = await import("../src/subtitles.ts");
		const result = await fetchSubtitles("no-captions-video");
		expect(result).toEqual([]);
	});

	it("skips tracks with missing baseUrl or languageCode", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => [
			{ name: { simpleText: "Bad" } },
			frTrack,
		]);
		const { fetchSubtitles } = await import("../src/subtitles.ts");
		const result = await fetchSubtitles("partial-video");
		expect(result).toHaveLength(1);
		expect(result[0].languageTag).toBe("fr");
	});

	it("refreshes an expired manual track and preserves translation", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => [
			{
				...frTrack,
				baseUrl: "https://www.youtube.com/api/timedtext?v=video&lang=fr&expire=999",
				vssId: ".fr",
			},
		]);
		mockYoutubeFetch.mockImplementationOnce(async () => new Response("", { status: 403 }));
		mockYoutubeFetch.mockImplementationOnce(
			async () => new Response("WEBVTT\n\n00:00.000 --> 00:01.000\nBonjour"),
		);
		const { fetchSubtitleContent } = await import("../src/subtitle-content.ts");
		const bytes = await fetchSubtitleContent(
			"https://www.youtube.com/api/timedtext?v=video&lang=fr&expire=1&tlang=es&fmt=ttml",
			mockYoutubeFetch,
		);
		const requested = new URL(String(mockYoutubeFetch.mock.calls.at(-1)?.[0]));
		const requestHeaders = new Headers(mockYoutubeFetch.mock.calls.at(-1)?.[1]?.headers);

		expect(new TextDecoder().decode(bytes).startsWith("WEBVTT")).toBe(true);
		expect(mockYoutubeFetch).toHaveBeenCalledTimes(2);
		expect(requested.searchParams.get("expire")).toBe("999");
		expect(requested.searchParams.get("fmt")).toBe("vtt");
		expect(requested.searchParams.get("tlang")).toBe("es");
		expect(requestHeaders.get("origin")).toBe("https://m.youtube.com");
		expect(requestHeaders.get("referer")).toBe("https://m.youtube.com/");
		expect(requestHeaders.get("user-agent")).toBe(MWEB_USER_AGENT);
	});

	it("selects the refreshed automatic track", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => [
			{ ...frTrack, languageCode: "en", vssId: ".en" },
			asrTrack,
		]);
		mockYoutubeFetch.mockImplementationOnce(async () => new Response("", { status: 403 }));
		mockYoutubeFetch.mockImplementationOnce(async () => new Response("WEBVTT\n\nAutomatic"));
		const { fetchSubtitleContent } = await import("../src/subtitle-content.ts");
		await fetchSubtitleContent(
			"https://www.youtube.com/api/timedtext?v=video&lang=en&kind=asr&expire=1",
			mockYoutubeFetch,
		);
		const requested = new URL(String(mockYoutubeFetch.mock.calls.at(-1)?.[0]));

		expect(requested.searchParams.get("kind")).toBe("asr");
		expect(requested.searchParams.get("expire")).toBe("999");
	});

	it("uses a current WEB track without replacing it through MWEB", async () => {
		mockFetchCaptionTracks.mockClear();
		mockYoutubeFetch.mockClear();
		mockYoutubeFetch.mockImplementationOnce(
			async () => new Response("WEBVTT\n\n00:00.000 --> 00:01.000\nCurrent"),
		);
		const { fetchSubtitleContent } = await import("../src/subtitle-content.ts");
		const bytes = await fetchSubtitleContent(
			"https://www.youtube.com/api/timedtext?v=video&lang=en&expire=999&fmt=ttml",
			mockYoutubeFetch,
		);
		const requested = new URL(String(mockYoutubeFetch.mock.calls[0]?.[0]));

		expect(new TextDecoder().decode(bytes).startsWith("WEBVTT")).toBe(true);
		expect(requested.hostname).toBe("www.youtube.com");
		expect(requested.searchParams.get("fmt")).toBe("vtt");
		expect(mockFetchCaptionTracks).not.toHaveBeenCalled();
		expect(mockYoutubeFetch).toHaveBeenCalledTimes(1);
	});

	it("returns a typed throttling failure without retrying", async () => {
		mockFetchCaptionTracks.mockImplementation(async () => [asrTrack]);
		mockYoutubeFetch.mockClear();
		mockYoutubeFetch.mockImplementation(async () => new Response("", { status: 429 }));
		const { fetchSubtitleContent, SubtitleFetchError } = await import("../src/subtitle-content.ts");
		const failure = await fetchSubtitleContent(
			"https://www.youtube.com/api/timedtext?v=video&lang=en&kind=asr",
			mockYoutubeFetch,
		).catch((error: unknown) => error);

		expect(failure).toBeInstanceOf(SubtitleFetchError);
		expect((failure as InstanceType<typeof SubtitleFetchError>).code).toBe(
			"subtitle_upstream_throttled",
		);
		expect(mockYoutubeFetch).toHaveBeenCalledTimes(1);
	});

	it("rejects non-YouTube subtitle URLs before fetching", async () => {
		mockYoutubeFetch.mockClear();
		const { fetchSubtitleContent, SubtitleFetchError } = await import("../src/subtitle-content.ts");
		const failure = await fetchSubtitleContent(
			"https://example.com/api/timedtext?v=video&lang=en",
			mockYoutubeFetch,
		).catch((error: unknown) => error);

		expect(failure).toBeInstanceOf(SubtitleFetchError);
		expect((failure as InstanceType<typeof SubtitleFetchError>).code).toBe(
			"subtitle_request_invalid",
		);
		expect(mockYoutubeFetch).not.toHaveBeenCalled();
	});
});
