import { fetchPoToken } from "./token-service.ts";
import { fetchCaptionTracks, type RawCaptionTrack } from "./youtube-caption-tracks.ts";

export type SubtitleTrack = {
	url: string;
	mimeType: string;
	languageTag: string;
	displayLanguageName: string;
	isAutoGenerated: boolean;
};

function toSubtitleTrack(raw: RawCaptionTrack): SubtitleTrack | null {
	const url = raw.baseUrl;
	const languageTag = raw.languageCode;
	if (typeof url !== "string" || typeof languageTag !== "string") return null;
	const displayLanguageName = raw.name?.simpleText ?? raw.name?.runs?.[0]?.text ?? languageTag;
	return {
		url,
		mimeType: "application/ttml+xml",
		languageTag,
		displayLanguageName,
		isAutoGenerated: raw.kind === "asr",
	};
}

export async function fetchSubtitles(videoId: string): Promise<SubtitleTrack[]> {
	const { visitorData, poToken } = await fetchPoToken(videoId);
	const raw = await fetchCaptionTracks(videoId, visitorData, poToken);
	return raw.flatMap((t) => {
		const track = toSubtitleTrack(t);
		return track ? [track] : [];
	});
}
