import { fetchPoToken } from "./token-service.ts";
import { fetchCaptionTracks, type RawCaptionTrack } from "./youtube-caption-tracks.ts";
import { youtubeFetch } from "./youtube-fetch.ts";
import { MWEB_USER_AGENT } from "./youtube-mweb-config.ts";

export type SubtitleErrorCode =
	| "subtitle_request_invalid"
	| "subtitle_track_not_found"
	| "subtitle_upstream_throttled"
	| "subtitle_upstream_unavailable"
	| "subtitle_payload_invalid";

export class SubtitleFetchError extends Error {
	constructor(
		message: string,
		readonly code: SubtitleErrorCode,
		readonly status: number,
	) {
		super(message);
	}
}

type SubtitleRequest = {
	videoId: string;
	languageTag: string;
	autoGenerated: boolean | null;
	translatedLanguageTag: string | null;
};

export async function fetchSubtitleContent(
	rawUrl: string,
	fetchYoutube: typeof youtubeFetch = youtubeFetch,
): Promise<Uint8Array> {
	const request = parseSubtitleRequest(rawUrl);
	const { visitorData, poToken } = await fetchPoToken(request.videoId);
	const tracks = await fetchCaptionTracks(request.videoId, visitorData, poToken);
	const track = selectTrack(tracks, request);
	if (!track?.baseUrl) {
		throw new SubtitleFetchError("Subtitle track not found", "subtitle_track_not_found", 404);
	}
	const response = await fetchYoutube(
		refreshedVttUrl(track.baseUrl, request.translatedLanguageTag),
		{
			headers: {
				accept: "text/vtt,*/*;q=0.8",
				origin: "https://m.youtube.com",
				referer: "https://m.youtube.com/",
				"user-agent": MWEB_USER_AGENT,
				"x-goog-visitor-id": visitorData,
			},
		},
	);
	if (response.status === 429) {
		throw new SubtitleFetchError(
			"YouTube temporarily throttled subtitle retrieval",
			"subtitle_upstream_throttled",
			429,
		);
	}
	if (!response.ok) {
		throw new SubtitleFetchError(
			`YouTube subtitle request failed: ${response.status}`,
			"subtitle_upstream_unavailable",
			502,
		);
	}
	const contentLength = Number(response.headers.get("content-length"));
	if (Number.isFinite(contentLength) && contentLength > MAX_SUBTITLE_BYTES) throw invalidPayload();
	const bytes = new Uint8Array(await response.arrayBuffer());
	if (
		bytes.length > MAX_SUBTITLE_BYTES ||
		!new TextDecoder().decode(bytes).trimStart().startsWith("WEBVTT")
	) {
		throw invalidPayload();
	}
	return bytes;
}

function parseSubtitleRequest(rawUrl: string): SubtitleRequest {
	let url: URL;
	try {
		url = new URL(rawUrl);
	} catch {
		throw invalidRequest();
	}
	if (
		url.protocol !== "https:" ||
		!isYoutubeHost(url.hostname) ||
		url.pathname !== "/api/timedtext"
	) {
		throw invalidRequest();
	}
	const videoId = url.searchParams.get("v")?.trim() ?? "";
	const languageTag = url.searchParams.get("lang")?.trim() ?? "";
	const translatedLanguageTag = url.searchParams.get("tlang")?.trim() || null;
	if (!videoId || videoId.length > 128 || !languageTag || languageTag.length > 64)
		throw invalidRequest();
	if (translatedLanguageTag && translatedLanguageTag.length > 64) throw invalidRequest();
	const vssId = url.searchParams.get("vssId");
	const kind = url.searchParams.get("kind");
	return {
		videoId,
		languageTag,
		autoGenerated:
			kind === null && vssId === null ? null : kind === "asr" || vssId?.startsWith("a.") === true,
		translatedLanguageTag,
	};
}

function selectTrack(
	tracks: RawCaptionTrack[],
	request: SubtitleRequest,
): RawCaptionTrack | undefined {
	const matchingLanguage = tracks.filter((track) => track.languageCode === request.languageTag);
	if (request.autoGenerated === null) {
		return matchingLanguage.find((track) => !isAutoGenerated(track)) ?? matchingLanguage[0];
	}
	return matchingLanguage.find((track) => isAutoGenerated(track) === request.autoGenerated);
}

function refreshedVttUrl(baseUrl: string, translatedLanguageTag: string | null): URL {
	const url = new URL(baseUrl, "https://m.youtube.com");
	if (
		url.protocol !== "https:" ||
		!isYoutubeHost(url.hostname) ||
		url.pathname !== "/api/timedtext"
	)
		throw invalidRequest();
	url.searchParams.set("fmt", "vtt");
	if (translatedLanguageTag) url.searchParams.set("tlang", translatedLanguageTag);
	else url.searchParams.delete("tlang");
	return url;
}

function isYoutubeHost(host: string): boolean {
	return host === "youtube.com" || host.endsWith(".youtube.com");
}

function isAutoGenerated(track: RawCaptionTrack): boolean {
	return track.kind === "asr" || track.vssId?.startsWith("a.") === true;
}

function invalidRequest(): SubtitleFetchError {
	return new SubtitleFetchError("Invalid YouTube subtitle URL", "subtitle_request_invalid", 400);
}

function invalidPayload(): SubtitleFetchError {
	return new SubtitleFetchError(
		"YouTube returned invalid subtitle content",
		"subtitle_payload_invalid",
		502,
	);
}

const MAX_SUBTITLE_BYTES = 5 * 1024 * 1024;
